### ISSUE TITLE
i succesfully installed but i dont see any packages

### ISSUE THREAD

**Issue by dikeckaan** [TGates71/Sentastico#7]
(sorry my english.) when i install Sentastico for my ubuntu 14.04 server i cant see any web apps in module i share picture link pls help me :smile: :+1: https://postimg.org/image/3zvahsnkj/

**Comment by dikeckaan** [comment]
i found how to solve it :+1:  i write only `zppy upgrade sentastico` its finished  succesfully

**Comment by TGates71** [comment]
Glad you sorted it out!
