### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by devinmcmanus** [TGates71/Sentastico#8]
Hi there,
I tried installing using the instructions here http://forums.sentora.org/showthread.php?tid=168 and got an error "No package match, check you have added the correct repo". I checked http://zppy-repo.mach-hosting.com/repo/index.php and noticed that Sentastico isn't in the list.
I cloned the repository on my local machine, zipped the contents of the sentastico folder and renamed it as sentastico.zpp. I was able to install this file through Sentora Module Admin but got this error when I tried to use it [https://i.postimg.cc/nLsgQYfL/add-pkg-error.png](https://i.postimg.cc/nLsgQYfL/add-pkg-error.png). After that, I tried running `zppy upgrade sentastico` and got this error [https://i.postimg.cc/rpvbG0qN/zppy-upgrade-error.png](https://i.postimg.cc/rpvbG0qN/zppy-upgrade-error.png)
Is Sentastico still alive?

**Comment by TGates71** [comment]
Updated and released for Sentora v2.0.0
