### ISSUE TITLE
same need update : Wp toolkit like . auto login and setup for wordpress and jumla . core block access 

### ISSUE THREAD

**Issue by imaauser23** [TGates71/Sentastico#9]
same need update : Wp toolkit like . auto login and setup for wordpress and jumla . core block access 
and no need add new install wite cammnd just install wite link like 👍  : bash link.com/sh 
and you ui is very bad you can update that to new icon and user update icons

**Comment by TGates71** [comment]
WordPress requires php 8. Sentora is not yet running php 8. I need to keep that in mind while adding packages. How is the ui 'very bad'? I just made a new update and more are to come.

**Comment by imaauser23** [comment]
thank you bro for update but i need same personal theme for ex : not show for demo sentora logo and 
better theme . 1 auto ssl 
2: upgrade php for own versin like 8.2 or 8.3.
3: WordPress Vulnerabilities
Security Measures
Check your site for known security vulnerabilities. Update or disable vulnerable WordPress assets.

Vulnerability scan was not run yet.

wp manger 💯 

4: install ruby 
change web server apache to inginx or back to apache multi web server

**Comment by imaauser23** [comment]
and how can i run surce python in setora ?

**Comment by imaauser23** [comment]
you can use Chat GPT for Help

**Comment by TGates71** [comment]
Not sure what you are talking about and how it is related to Sentastico.
